# Generated by Django 4.1.2 on 2022-11-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
